models:

  logistic_regression:
    C: 1.0
    max_iter: 1000
    class_weight: balanced

  random_forest:
    n_estimators: 50
    max_depth: 12
    min_samples_split: 5
    class_weight: balanced
    random_state: 42

  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    scale_pos_weight: 7.61
    random_state: 42